name: Bug Report
description: Report a bug or issue with Quant.Explorer
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us understand and reproduce the issue.

  - type: input
    id: version
    attributes:
      label: Quant.Explorer Version
      description: Which version of Quant.Explorer are you using?
      placeholder: "e.g., 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: Data Provider
      description: Which data provider were you using when the issue occurred?
      options:
        - Yahoo Finance
        - Alpha Vantage
        - Binance
        - CoinGecko
        - Twelve Data
        - Multiple providers
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Call function with parameters...
        2. See error...
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: elixir
      placeholder: |
        # Minimal code sample
        {:ok, df} = Quant.Explorer.history("AAPL", provider: :yahoo_finance)

  - type: textarea
    id: error
    attributes:
      label: Error Message/Output
      description: If applicable, add the full error message or unexpected output
      render: text
      placeholder: Paste the error message here

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - Elixir version: 
        - Erlang/OTP version: 
        - Operating System: 
        - Explorer version: 
      value: |
        - Elixir version: 
        - Erlang/OTP version: 
        - Operating System: 
        - Explorer version: 
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, logs, etc.)